version: "3.0"
services:
    db:
        image: postgres
        container_name: postgres_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: vtrackng
        ports:
            - "5432:5432"
    admin-console:
        container_name: admin-console
        build:
            context: ./admin-console/
            target: ${NODE_ENV:-development}
            args:
                NODE_ENV: ${NODE_ENV:-development}
        ports:
            - 3100:3100
        develop:
            watch:
                - action: sync
                  path: ./admin-console/
                  target: /usr/src/app
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: ./admin-console/package.json
    api-server:
        container_name: api-server
        build:
            context: ./api-server/
            target: ${NODE_ENV:-development}
            args:
                NODE_ENV: ${NODE_ENV:-development}
        env_file:
            - ./api-server/.env.docker
        ports:
            - 3000:3000
        depends_on:
            - db
        develop:
            watch:
                - action: sync
                  path: ./api-server/
                  target: /usr/src/app
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: ./api-server/package.json
